### ISSUE TITLE
need help rewrite code for other picamera

### ISSUE THREAD

**Issue by cbogithub** [EdjeElectronics/OpenCV-Playing-Card-Detector#1]
Hi, guy

i interesting for your code but i have not picamera , so i rewrite your code and need your help to complete it.
my question:
what codes in block can replace with ?:

```
    # for frame in camera.capture_continuous(rawCapture, format="bgr",use_video_port=True):
    #
    #     image = frame.array
    #
    #     cv2.imshow("Card",image)
    #
    #     key = cv2.waitKey(1) & 0xFF
    #     if key == ord("p"):
    #         break
    #
    #     rawCapture.truncate(0)
```

**Comment by EdjeElectronics** [comment]
I modified the code to support either a USB or the PiCamera. Please see the instructions in the readme or in the code itself for how to use a USB camera.
