### ISSUE TITLE
Not enough values to unpack error?

### ISSUE THREAD

**Issue by sasinivd** [EdjeElectronics/OpenCV-Playing-Card-Detector#12]
Traceback (most recent call last):
  File "E:\OpenCV-Playing-Card-Detector-master\CardDetector.py", line 66, in <module>
    cnts_sort, cnt_is_card = Cards.find_cards(pre_proc)
  File "E:\OpenCV-Playing-Card-Detector-master\Cards.py", line 135, in find_cards
    dummy,cnts,hier = cv2.findContours(thresh_image,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by ghost** [comment]
The function cv2.findContours() has been changed to return only the contours and the hierarchy.

so in Cards.py:

`dummy, cnts, hier = cv2.findContours(thresh_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`

should be

`cnts, hier = cv2.findContours(thresh_image, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)`

Also remove dummy everywhere cv2.findContours() is been called (in Cards.py and Rank_Suit_Isolator.py).

**Comment by EdjeElectronics** [comment]
Thanks for helping out @material5! Darn cv2 updates :)
