### ISSUE TITLE
I need help. But firstly, thank you for your program.

### ISSUE THREAD

**Issue by gnurtw** [EdjeElectronics/OpenCV-Playing-Card-Detector#13]
So I have a homework that has to detect something with openCV. And I'm interested in your study.
I've followed the instructions that you made to detect cards. After messing around with errors. I successfully detected cards. But there's a problem for me: 
Not all the time I show the card it can be detected. In your video, you need a dark background. But I'm using my laptop's cam so I just show the cards in front of it. When the lights on my room's off, the program's working just fine. But when I turn on the lights (maybe my background's lighter?), it cannot detect contours and identify cards.
What should I do to make it work all the time?
Thank you for reading. Hope you can help me out!

**Comment by EdjeElectronics** [comment]
Hi @gnurtw, I know I'm probably replying way too late, but you should check out my machine learning object detection videos. I trained a neural network to recognize cards against busy backgrounds, it works much better than this approach (although it takes much more processing power)!

https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10
